version: "3.3"

services:
  backend:
    build: ./backend
    container_name: tp-backend
    ports:
      - "3000:3000" # Host: Container (Backend accessible on localhost:3000)
    networks:
      - webnet
    depends_on:
      - db # Backend depends on the database
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=mydb

  frontend:
    build: ./frontend
    container_name: tp-frontend
    ports:
      - "8080:80" # Frontend accessible on localhost:8080
    depends_on:
      - backend
    networks:
      - webnet

  db:
    build: ./database # Build from the Dockerfile in the database directory
    container_name: tp-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - "5432:5432" # Optional: Local access to the database

networks:
  webnet: # Custom bridge network for communication between services

volumes:
  db-data: # Named volume for persistent data storage

