name: CI - Build Docker Images

on:
  push:
    branches: 
      - main  # Le pipeline se déclenche sur un push vers la branche 'main'
  pull_request:
    branches: 
      - main  # Le pipeline se déclenche lors des pull requests vers la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Environnement du runner

    steps:
      # Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construction de l'image Docker pour le backend
      - name: Build Backend Image
        run: |
          docker build -t tp-backend ./backend

      # Construction de l'image Docker pour le frontend
      - name: Build Frontend Image
        run: |
          docker build -t tp-frontend ./frontend

      # Construction de l'image Docker pour la base de données
      - name: Build Database Image
        run: |
          docker build -t tp-db ./database

      # Liste des images Docker créées
      - name: List Docker Images
        run: |
          docker images

